# Anomaly Detection App 的配置文件
# 定义模型加载模式，可选值：preload（预加载所有模型）或 ondemand（按需加载）
load_mode: preload
# 模型配置, key 为模型名称，value 为模型路径
models:
  Metal Nut: models/mvtec_metal_nut/ckpt.pth
  Screw: models/mvtec_screw/ckpt.pth
# 异常判断阈值
threshold: 1.20
