batch:
  max_batch_size: 16
  max_batch_threads: 10
load_mode: preload
models:
  Metal Nut: models/mvtec_metal_nut/ckpt.pth
preload:
  max_memory_mb: 1024
  max_preload_threads: 9
  preload_chunk_size: 50
  use_disk_cache: true
threshold: 1.09
